name: TOX testing

"on":
  push:
  pull_request:

jobs:
  tox:
    runs-on: ubuntu-latest
    env:
      TOX_PARALLEL_NO_SPINNER: 1  # Removes logging spam
    steps:
      - name: Checkout and setup Pythons
        uses: actions/checkout@v2
        with:
          python-version: '3.8'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install tox and run tests
        run: |
          make install
          pip install tox
          tox --parallel
